saved_dir: /home/s/syan/Models/exp110821

train_root_dir: /home/s/NeoDataset-1300-440/images/
train_txt_path:
  - /home/s/syan/neoplasm_segmentation/config/train.txt
  - /home/s/syan/neoplasm_segmentation/config/train_only_non.txt
  - /home/s/syan/neoplasm_segmentation/config/train_only_non.txt
  - /home/s/syan/neoplasm_segmentation/config/train_only_non.txt
  - /home/s/syan/neoplasm_segmentation/config/train_only_non.txt
  - /home/s/syan/neoplasm_segmentation/config/train_only_non.txt
test_root_dir: /home/s/NeoDataset-1300/images/
test_txt_path: /home/s/syan/neoplasm_segmentation/config/test.txt

# Color 
mask_values:
  polyp: [255, 255, 255]
  neoplastic: [255, 0, 0]
  non-neoplastic: [0, 255, 0]
  undefined: [255, 255, 0]

# Training size
height: 352
width: 352

# Training params
lr: 1e-3
min_lr: 0
batch_size: 16
num_epoch: 50
warmup_epoch: 10
weight_decay: 1e-4